# Generated by Django 3.2.3 on 2021-05-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scratchapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userid",
            field=models.IntegerField(auto_created=1, default=1),
            preserve_default=False,
        ),
    ]
